version: '3'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: postgres://sampleuser:Passw0rd@db:5432/sampledb
      TZ: Asia/Tokyo
    depends_on:
      - db
    tty: true
  db:
    build: postgres
    # image: postgres:10.3
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: sampledb
      # LANG: ja_JP.UTF-8
      # LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
      LC_CTYPE: ja_JP.UTF-8
      TZ: Asia/Tokyo
    tty: true
